### PR TITLE
Update rmapi to v0.0.25

### PR DESCRIPTION
**Pull request by nov1n**
* Fixes the issue authenticating to the Remarkable API.
* Speeds up building the document tree on startup.
* Adds a script to automate updating `rmapi` binaries.

### CODE REVIEW

**Comment by vincentclaes** [comment]
This seems to work 🥳

```
cd ~
rm -rf .rmapi-cache
rm .rmapi
rm .remarkable-pocket


 touch ~/.remarkable-pocket ~/.rmapi && mkdir -p ~/.rmapi-cache && docker run -it --env TZ=Europe/Amsterdam -p 65112:65112 -v ~/.remarkable-pocket:/root/.remarkable-pocket -v ~/.rmapi:/root/.rmapi -v ~/.rmapi-cache:/root/.cache/rmapi ghcr.io/nov1n/remarkable-pocket:0.4.0 -v

```

**Comment by nov1n** [comment]
Please be careful running this with software version 3.x. During my testing, I encountered some strange behavior, which is why I haven't merged this PR yet.

As stated above: use at your own risk.

**Comment by vincentclaes** [comment]
> Please be careful running this with software version 3.x. During my testing, I encountered some strange behavior, which is why I haven't merged this PR yet.
> 
> As stated above: use at your own risk.

yep, but it seems to work on my end :)
Bought you a coffee! thanks a lot for making this. You should make a micro saas out of this!

**Comment by nov1n** [comment]
I'm glad you find it useful and thanks for the coffee. Much appreciated! (:

**Comment by nov1n** [comment]
rmapi `v0.0.25` fixed the problems that I observed. You might want to pull the new `0.0.4` and run that instead just to be sure!

**Pull request merged**
